name: medical_tourism_mgt

# sdkPath: .fvm/flutter_sdk

ide:
  intellij: true

command:
  bootstrap:
    runPubGetInParallel: false

packages:
  - .
  - modules/**

scripts:
  setup:
    description: "Install necessary plug-ins and bootstrap the workspace"
    run: |
      dart pub global activate fvm && \
      fvm install $FLUTTER_VERSION && \
      fvm use $FLUTTER_VERSION && \
      dart pub global activate spider && \
      brew install lefthook && \
      lefthook install && \
      melos bootstrap && \
      fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml && \
      fvm dart run flutter_native_splash:create --path=flutter_native_splash.yaml
    env:
      FLUTTER_VERSION: 3.19.5
  flutter:use:
    description: "Use flutter version"
    run: |
      fvm use $FLUTTER_VERSION && \
      fvm global $FLUTTER_VERSION && \
      dart pub global activate spider
    env:
      FLUTTER_VERSION: 3.19.5
  run_debug:
    description: "run_debug"
    run: fvm flutter run -d chrome --web-port 5555
  pub:add:
    description: "Add pub for all modules"
    run: melos exec -- \ fvm flutter pub add
  pub:get:
    description: "Sync pub for all modules"
    run: melos exec -- \ fvm flutter pub get
  pub:upgrade:
    description: "Upgrade pub for all modules"
    run: melos exec -- \ fvm flutter pub upgrade --major-versions
  pod:install:
    description: "Run pod install for iOS"
    run: |
      cd ios && \
      pod install --repo-update
  pod:update:
    description: "Run pod update for iOS"
    run: |
      cd ios && \
      pod update
  build_runner:
    description: "Generate *.g.dart files on modules which depends on build_runner"
    run: melos exec --depends-on="build_runner" fvm dart run build_runner build --delete-conflicting-outputs
  fixer:
    description: "Autofix dart files with import_sorter"
    run: melos exec "lefthook run fixer"
  sort_imports:
    description: "Sort imports"
    run: melos exec -- \ fvm flutter pub run import_sorter:main
  dart_fix:
    description: "Apply dart fix"
    run: melos exec -- \ fvm dart fix --apply
  gen-l10n:
    description: "Generate localized strings"
    run: melos exec --scope="core_l10n" -- \ fvm flutter gen-l10n
  gen-assets:
    description: "Generate assets of images and icons"
    run: |
      melos exec --scope="core_ui" -- \ spider build && \
      melos exec --scope="core_ui" -- \ fvm flutter pub run icon_font_generator:generator
  gen-appicon:
    description: "Generate app icon for android and ios"
    run: |
      melos exec -c 6 --fail-fast -- \ fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons*
    packageFilters:
      scope: "medical_tourism_mgt"


  setup_win:
    description: "Install necessary plug-ins and bootstrap the workspace"
    run: |
      dart pub global activate fvm && ^
      fvm install %FLUTTER_VERSION% && ^
      fvm use %FLUTTER_VERSION% && ^
      dart pub global activate spider && ^
      melos bootstrap
    env:
      FLUTTER_VERSION: 3.19.5
  build_runner_win:
    description: "Generate *.g.dart files on modules which depends on build_runner"
    run: melos exec --depends-on="build_runner" fvm dart run build_runner build --delete-conflicting-outputs
  fixer_win:
    description: "Autofix dart files with import_sorter"
    run: melos exec "lefthook run fixer"
  gen_api_win:
    description: "Generate api files"
    run: melos exec --scope="core_network" -- fvm dart run build_runner build --delete-conflicting-outputs
  gen_l10n_win:
    description: "Generate localized strings"
    run: melos exec --scope="core_l10n" -- fvm flutter gen-l10n
  gen_assets_win:
    description: "Generate assets of images and icons"
    run: |
      melos exec --scope="core_ui" -- spider build && ^
      melos exec --scope="core_ui" -- fvm flutter pub run icon_font_generator:generator
  gen_appicon_win:
    description: "Generate app icon for android and ios"
    run: |
      melos exec -c 6 --fail-fast -- fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons*
    packageFilters:
      scope: "medical_tourism_mgt"



  
  feature_home:
    description: "Generate feature_home"
    run: melos exec --scope="feature_home" -- fvm dart run build_runner build --delete-conflicting-outputs

